### ISSUE TITLE
404 error on dashboard, admin menu

### ISSUE THREAD

**Issue by dehypnosis** [luhis/CodeGolf#1]
Hi Matt! Good luck to your service.

Anyway I have found a small bug.
After signed in with Github account, I encountered an error message on dashboard and admin tab.
Redirected to https://www.codegolf.ga/Account/AccessDenied?ReturnUrl=%2Fdashboard but got 404.

**Comment by luhis** [comment]
thanks for this.  Fixed in 8ba63, i just moved it to the default 403 error page
